#!/usr/bin/env python

import xml.parsers.expat
import pymongo

from pymongo import Connection

# Each of our data files which will be used as collection names also.
files = [ "badges", "comments", "posts", "users", "votes" ]

connection = Connection()

# Name our database, can change this for Server Fault/etc..
db = connection['stackoverflow']

for file in files:

  print "init import: %s.xml" % file
  collection = db[file]

  def start_element(name, attrs):
    # attributes are all ready dict's of the right format, how convenient!
    collection.insert( attrs )

  parser = xml.parsers.expat.ParserCreate()
  parser.StartElementHandler = start_element
  parser.ParseFile( open( file + ".xml", "r") )

  print "imported %s %s" % ( collection.count() , files )
  print "finished import: %s.xml" % file

